// <auto-generated />
using System;
using EasyHideout.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyHideout.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("EasyHideout.Models.AppSettings", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int?>("ActiveProfileId").HasColumnType("INTEGER");
                    b.Property<int>("ApiRefreshIntervalMinutes").HasDefaultValue(60).HasColumnType("INTEGER");
                    b.Property<string>("ApiRefreshMode").IsRequired().HasDefaultValue("Manual").HasColumnType("TEXT");
                    b.Property<string>("DetailPanelPosition").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("ItemNameDisplay").IsRequired().HasDefaultValue("Both").HasColumnType("TEXT");
                    b.Property<DateTime?>("LastApiRefresh").HasColumnType("TEXT");
                    b.Property<int?>("PriorityL1Show").HasColumnType("INTEGER");
                    b.Property<int?>("PriorityL2Show").HasColumnType("INTEGER");
                    b.Property<string>("Theme").IsRequired().HasColumnType("TEXT");
                    b.Property<double?>("WindowHeight").HasColumnType("REAL");
                    b.Property<double?>("WindowLeft").HasColumnType("REAL");
                    b.Property<double?>("WindowTop").HasColumnType("REAL");
                    b.Property<double?>("WindowWidth").HasColumnType("REAL");
                    b.HasKey("Id");
                    b.HasIndex("ActiveProfileId");
                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("EasyHideout.Models.FocusNode", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("ProfileId").HasColumnType("INTEGER");
                    b.Property<int>("StationId").HasColumnType("INTEGER");
                    b.Property<int>("TargetLevel").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("ProfileId").IsUnique();
                    b.HasIndex("StationId");
                    b.ToTable("FocusNodes");
                });

            modelBuilder.Entity("EasyHideout.Models.HideoutLevel", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("Level").HasColumnType("INTEGER");
                    b.Property<int>("StationId").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("StationId");
                    b.ToTable("HideoutLevels");
                });

            modelBuilder.Entity("EasyHideout.Models.HideoutStation", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("MaxLevel").HasColumnType("INTEGER");
                    b.Property<string>("Name").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("NormalizedName").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("TarkovStationId").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("TarkovStationId").IsUnique();
                    b.ToTable("HideoutStations");
                });

            modelBuilder.Entity("EasyHideout.Models.IgnoredItem", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime>("DateAdded").HasColumnType("TEXT");
                    b.Property<string>("ItemName").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Note").HasColumnType("TEXT");
                    b.Property<int>("ProfileId").HasColumnType("INTEGER");
                    b.Property<string>("TarkovItemId").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("ProfileId", "TarkovItemId").IsUnique();
                    b.ToTable("IgnoredItems");
                });

            modelBuilder.Entity("EasyHideout.Models.ImportantItem", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("ItemName").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("ProfileId").HasColumnType("INTEGER");
                    b.Property<string>("TarkovItemId").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("ProfileId", "TarkovItemId").IsUnique();
                    b.ToTable("ImportantItems");
                });

            modelBuilder.Entity("EasyHideout.Models.ItemCount", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("ItemName").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("ProfileId").HasColumnType("INTEGER");
                    b.Property<int>("QuantityOwned").HasColumnType("INTEGER");
                    b.Property<string>("TarkovItemId").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("ProfileId", "TarkovItemId").IsUnique();
                    b.ToTable("ItemCounts");
                });

            modelBuilder.Entity("EasyHideout.Models.ItemPriceSnapshot", b =>
                {
                    b.Property<string>("TarkovItemId").HasColumnType("TEXT");
                    b.Property<int>("PreviousAvgPrice").HasColumnType("INTEGER");
                    b.Property<DateTime>("SnapshotAt").HasColumnType("TEXT");
                    b.HasKey("TarkovItemId");
                    b.ToTable("ItemPriceSnapshots");
                });

            modelBuilder.Entity("EasyHideout.Models.ItemRequirement", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("AvgPrice").HasDefaultValue(0).HasColumnType("INTEGER");
                    b.Property<bool>("FoundInRaid").HasDefaultValue(false).HasColumnType("INTEGER");
                    b.Property<int>("HideoutLevelId").HasColumnType("INTEGER");
                    b.Property<string>("IconUrl").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("ItemName").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("MinLevelForFlea").HasDefaultValue(0).HasColumnType("INTEGER");
                    b.Property<int>("Quantity").HasColumnType("INTEGER");
                    b.Property<string>("ShortName").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("TarkovItemId").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("HideoutLevelId");
                    b.ToTable("ItemRequirements");
                });

            modelBuilder.Entity("EasyHideout.Models.Profile", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("CharacterLevel").HasColumnType("INTEGER").HasDefaultValue(1);
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<string>("Edition").IsRequired().HasDefaultValue("Standard").HasColumnType("TEXT");
                    b.Property<string>("Name").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("EasyHideout.Models.ProfileStationLevel", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("CurrentLevel").HasColumnType("INTEGER");
                    b.Property<int>("ProfileId").HasColumnType("INTEGER");
                    b.Property<int>("StationId").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("StationId");
                    b.HasIndex("ProfileId", "StationId").IsUnique();
                    b.ToTable("ProfileStationLevels");
                });

            modelBuilder.Entity("EasyHideout.Models.StationDependency", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("HideoutLevelId").HasColumnType("INTEGER");
                    b.Property<int>("RequiredLevel").HasColumnType("INTEGER");
                    b.Property<int>("RequiredStationId").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("HideoutLevelId");
                    b.HasIndex("RequiredStationId");
                    b.ToTable("StationDependencies");
                });

            modelBuilder.Entity("EasyHideout.Models.TraderLoyaltyLevel", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("LoyaltyLevel").HasColumnType("INTEGER");
                    b.Property<int>("RequiredPlayerLevel").HasColumnType("INTEGER");
                    b.Property<string>("TraderId").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("TraderName").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("TraderId", "LoyaltyLevel").IsUnique();
                    b.ToTable("TraderLoyaltyLevels");
                });

            modelBuilder.Entity("EasyHideout.Models.TraderRequirement", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("HideoutLevelId").HasColumnType("INTEGER");
                    b.Property<int>("RequiredLoyaltyLevel").HasColumnType("INTEGER");
                    b.Property<string>("TraderId").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("TraderName").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("HideoutLevelId");
                    b.ToTable("TraderRequirements");
                });

            modelBuilder.Entity("EasyHideout.Models.AppSettings", b =>
                {
                    b.HasOne("EasyHideout.Models.Profile", "ActiveProfile").WithMany().HasForeignKey("ActiveProfileId");
                    b.Navigation("ActiveProfile");
                });

            modelBuilder.Entity("EasyHideout.Models.FocusNode", b =>
                {
                    b.HasOne("EasyHideout.Models.Profile", "Profile").WithOne("FocusNode")
                        .HasForeignKey("EasyHideout.Models.FocusNode", "ProfileId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("EasyHideout.Models.HideoutStation", "Station").WithMany()
                        .HasForeignKey("StationId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Profile");
                    b.Navigation("Station");
                });

            modelBuilder.Entity("EasyHideout.Models.HideoutLevel", b =>
                {
                    b.HasOne("EasyHideout.Models.HideoutStation", "Station").WithMany("Levels")
                        .HasForeignKey("StationId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Station");
                });

            modelBuilder.Entity("EasyHideout.Models.IgnoredItem", b =>
                {
                    b.HasOne("EasyHideout.Models.Profile", "Profile").WithMany("IgnoredItems")
                        .HasForeignKey("ProfileId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Profile");
                });

            modelBuilder.Entity("EasyHideout.Models.ImportantItem", b =>
                {
                    b.HasOne("EasyHideout.Models.Profile", "Profile").WithMany("ImportantItems")
                        .HasForeignKey("ProfileId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Profile");
                });

            modelBuilder.Entity("EasyHideout.Models.ItemCount", b =>
                {
                    b.HasOne("EasyHideout.Models.Profile", "Profile").WithMany("ItemCounts")
                        .HasForeignKey("ProfileId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Profile");
                });

            modelBuilder.Entity("EasyHideout.Models.ItemRequirement", b =>
                {
                    b.HasOne("EasyHideout.Models.HideoutLevel", "HideoutLevel").WithMany("ItemRequirements")
                        .HasForeignKey("HideoutLevelId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("HideoutLevel");
                });

            modelBuilder.Entity("EasyHideout.Models.ProfileStationLevel", b =>
                {
                    b.HasOne("EasyHideout.Models.Profile", "Profile").WithMany("StationLevels")
                        .HasForeignKey("ProfileId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("EasyHideout.Models.HideoutStation", "Station").WithMany("ProfileStationLevels")
                        .HasForeignKey("StationId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Profile");
                    b.Navigation("Station");
                });

            modelBuilder.Entity("EasyHideout.Models.StationDependency", b =>
                {
                    b.HasOne("EasyHideout.Models.HideoutLevel", "HideoutLevel").WithMany("StationDependencies")
                        .HasForeignKey("HideoutLevelId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("EasyHideout.Models.HideoutStation", "RequiredStation").WithMany()
                        .HasForeignKey("RequiredStationId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("HideoutLevel");
                    b.Navigation("RequiredStation");
                });

            modelBuilder.Entity("EasyHideout.Models.TraderRequirement", b =>
                {
                    b.HasOne("EasyHideout.Models.HideoutLevel", "HideoutLevel").WithMany("TraderRequirements")
                        .HasForeignKey("HideoutLevelId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("HideoutLevel");
                });

            modelBuilder.Entity("EasyHideout.Models.HideoutLevel", b =>
                {
                    b.Navigation("ItemRequirements");
                    b.Navigation("StationDependencies");
                    b.Navigation("TraderRequirements");
                });

            modelBuilder.Entity("EasyHideout.Models.HideoutStation", b =>
                {
                    b.Navigation("Levels");
                    b.Navigation("ProfileStationLevels");
                });

            modelBuilder.Entity("EasyHideout.Models.Profile", b =>
                {
                    b.Navigation("FocusNode");
                    b.Navigation("IgnoredItems");
                    b.Navigation("ImportantItems");
                    b.Navigation("ItemCounts");
                    b.Navigation("StationLevels");
                });
#pragma warning restore 612, 618
        }
    }
}
